package forward;
import com.ftn.sbnz.model.models.Player;
import com.ftn.sbnz.model.models.PlayerStatus;


query hasStyle( String player, String playerWithThatStyle, String team )
  Player(player==name,playerStyle != null, playerWithThatStyle==playerStyle.name, nbaTeam.getName()== team)
  or
  ( Player( z:name, playerStyle != null, playerWithThatStyle==playerStyle.name ) and hasStyle( player, z, team; ) )
end

rule "Find players with similar style on the same team"
when
    $player : Player(status == PlayerStatus.OUT)
    hasStyle( similarPlayer, $player.name, $player.nbaTeam.name; )
then
    System.out.println("Found player with similar style: " + similarPlayer);
end


