version: '3.7'
services:
    postgres:
        image: postgres:latest
        container_name: sbnz_postgres
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: nbafantasy
        ports:
            - "5432:5432"
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
