package forward;

import com.ftn.sbnz.model.models.stats.FantasyStatisticalColumns;
import com.ftn.sbnz.model.models.Player
import com.ftn.sbnz.model.models.NBATeam
import java.util.ArrayList
import java.util.List
import java.util.Collections
import java.util.stream.Collectors
import java.util.Comparator;



query "getMostSelectedPlayersByThreshold" (int threshold)
    $player : Player( fantasyStatisticalColumns!=null, fantasyStatisticalColumns.timesSelected > threshold)
end

query "getMostSelectedPlayersByNBATeamName" (String team)
    $player : Player( nbaTeam.name == team, fantasyStatisticalColumns!=null, fantasyStatisticalColumns.timesSelected > 0)
end


query "getTeamsWithSelectedPlayers"
    $team : NBATeam()
    $count : Number(intValue > 0) from accumulate(
        $p : Player(nbaTeam == $team, fantasyStatisticalColumns!=null, fantasyStatisticalColumns.timesSelected > 0),
        count($p)
    )
end

